import path from 'node:path';

/**
 * Validate that a caller-influenced archive ID is a plain UUID before it is
 * ever joined into a filesystem path. Archive IDs are always generated by
 * us (crypto.randomUUID()); this guard exists so that even a bug elsewhere
 * (or a compromised renderer trying to smuggle a crafted ID through IPC)
 * cannot turn into a path-traversal write/read.
 */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isValidArchiveId(id: string): boolean {
  return UUID_RE.test(id);
}

export function assertValidArchiveId(id: string): void {
  if (!isValidArchiveId(id)) {
    throw new Error(`Refusing to use non-UUID archive id: ${JSON.stringify(id)}`);
  }
}

/**
 * Resolve `<archivesRoot>/<archiveId>` and verify the result is actually
 * inside archivesRoot. Defense in depth on top of assertValidArchiveId --
 * if archivesRoot ever changes or archiveId validation is ever loosened,
 * this still stops traversal.
 */
export function archiveDirFor(archivesRoot: string, archiveId: string): string {
  assertValidArchiveId(archiveId);
  const root = path.resolve(archivesRoot);
  const dir = path.resolve(root, archiveId);
  if (dir !== root && !dir.startsWith(root + path.sep)) {
    throw new Error('Refusing to use archive directory outside archives root');
  }
  return dir;
}

export function archiveFilePaths(archivesRoot: string, archiveId: string) {
  const dir = archiveDirFor(archivesRoot, archiveId);
  return {
    dir,
    mhtml: path.join(dir, 'page.mhtml'),
    screenshot: path.join(dir, 'screenshot.png'),
    text: path.join(dir, 'text.txt'),
    metadata: path.join(dir, 'metadata.json'),
    favicon: path.join(dir, 'favicon.png'),
  };
}
